In [1]:
# importing required libriaries 
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
# importing train dataset
WNS_train_file = pd.read_csv('WNS_Train.csv')

# setting train file as dataframe

WNS_train_dframe = DataFrame(WNS_train_file)

WNS_train_dframe.head()

employee_id         department  Sales & Marketing  Operations  Technology  \
0        65438  Sales & Marketing                  1           0           0   
1        65141         Operations                  0           1           0   
2         7513  Sales & Marketing                  1           0           0   
3         2542  Sales & Marketing                  1           0           0   
4        48945         Technology                  0           0           1   

   Analytics  R&D  Procurement  Finance  HR     ...       gender  \
0          0    0            0        0   0     ...            f   
1          0    0            0        0   0     ...            m   
2          0    0            0        0   0     ...            m   
3          0    0            0        0   0     ...            m   
4          0    0            0        0   0     ...            m   

  recruitment_channel no_of_trainings  age  previous_year_rating  \
0            sourcing               1   35                     5   
1               other               1   30                     5   
2            sourcing               1   34                     3   
3               other               2   39                     1   
4               other               1   45                     3   

   length_of_service KPIs_met >80% awards_won?  avg_training_score  \
0                  8             1           0                  49   
1                  4             0           0                  60   
2                  7             0           0                  50   
3                 10             0           0                  50   
4                  2             0           0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0  

[5 rows x 26 columns]

In [3]:
X = WNS_train_dframe.iloc[:,[2,3,4,5,6,7,8,9,10,13,14,15,18,19,20,21,22,23,24]].values

Y = WNS_train_dframe.iloc[:,[25]].values

# splitting train dataset to check model accuracy
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 0)

In [4]:
SC = StandardScaler()

X_train = SC.fit_transform(X_train)
X_test = SC.fit_transform(X_test)

C:\Users\Akshay\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
RF_Classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state = 0)

In [6]:
RF_Classifier.fit(X_train, Y_train)

C:\Users\Akshay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [7]:
Y_pred = RF_Classifier.predict(X_test)

Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [8]:
WNS_train_dframe.groupby('is_promoted').mean()

employee_id  Sales & Marketing  Operations  Technology  \
is_promoted                                                            
0            39187.520423           0.311667    0.205923    0.127044   
1            39285.092331           0.259854    0.219152    0.164524   

             Analytics       R&D  Procurement  Finance        HR     Legal  \
is_promoted                                                                  
0             0.096530  0.018548     0.128640  0.04647  0.045513  0.019665   
1             0.109683  0.014781     0.147386  0.04413  0.029135  0.011354   

             Master's & above  Bachelor's  Below Secondary  no_of_trainings  \
is_promoted                                                                   
0                    0.268329    0.671340         0.014719         1.257639   
1                    0.315124    0.644387         0.014353         1.203299   

                   age  previous_year_rating  length_of_service  \
is_promoted                                                       
0            34.844037              3.021221           5.879398   
1            34.372965              3.696658           5.716367   

             KPIs_met >80%  awards_won?  avg_training_score  
is_promoted                                                  
0                 0.319685     0.014180           62.647686  
1                 0.698800     0.119751           71.325193

In [9]:
from sklearn.metrics import confusion_matrix

RF_confusion_matrix = confusion_matrix(Y_test, Y_pred)

RF_confusion_matrix

array([[12304,   244],
       [  738,   416]], dtype=int64)

In [24]:
RF_Classifier.score(X_test, Y_test)

0.928331630418917

In [11]:
RF_acc = accuracy_score(Y_test, Y_pred)

RF_acc

0.928331630418917

In [12]:
from sklearn.metrics import f1_score

f1_score(Y_test, Y_pred, average='micro')

0.928331630418917

In [13]:
f1_score(Y_test, Y_pred, average='weighted')

0.9192647956505534

In [14]:
# importing test dataset
WNS_test_file = pd.read_csv('WNS_Test.csv')

# setting test file as dataframe

WNS_test_dframe = DataFrame(WNS_test_file)

WNS_test_dframe.head()

employee_id         department  Sales & Marketing  Operations  Technology  \
0         8724         Technology                  0           0           1   
1        74430                 HR                  0           0           0   
2        72255  Sales & Marketing                  1           0           0   
3        38562        Procurement                  0           0           0   
4        64486            Finance                  0           0           0   

   Analytics  R&D  Procurement  Finance  HR         ...          \
0          0    0            0        0   0         ...           
1          0    0            0        0   1         ...           
2          0    0            0        0   0         ...           
3          0    0            1        0   0         ...           
4          0    0            0        1   0         ...           

   Below Secondary gender recruitment_channel  no_of_trainings  age  \
0                0      m            sourcing                1   24   
1                0      f               other                1   31   
2                0      m               other                1   31   
3                0      f               other                3   31   
4                0      m            sourcing                1   30   

   previous_year_rating length_of_service KPIs_met >80%  awards_won?  \
0                     0                 1             1            0   
1                     3                 5             0            0   
2                     1                 4             0            0   
3                     2                 9             0            0   
4                     4                 7             0            0   

   avg_training_score  
0                  77  
1                  51  
2                  47  
3                  65  
4                  61  

[5 rows x 25 columns]

In [15]:
X1 = WNS_test_dframe.iloc[:,[2,3,4,5,6,7,8,9,10,13,14,15,18,19,20,21,22,23,24]].values

X1 = SC.fit_transform(X1)

C:\Users\Akshay\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [16]:
# predicted values for promotion from test dataset
Y1_pred = RF_Classifier.predict(X1)

Y1_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
WNS_test_dframe['is_promoted'] = Y1_pred

WNS_test_dframe[['employee_id','is_promoted']].head()

employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

In [18]:
WNS_train_dframe.groupby('is_promoted').mean()

employee_id  Sales & Marketing  Operations  Technology  \
is_promoted                                                            
0            39187.520423           0.311667    0.205923    0.127044   
1            39285.092331           0.259854    0.219152    0.164524   

             Analytics       R&D  Procurement  Finance        HR     Legal  \
is_promoted                                                                  
0             0.096530  0.018548     0.128640  0.04647  0.045513  0.019665   
1             0.109683  0.014781     0.147386  0.04413  0.029135  0.011354   

             Master's & above  Bachelor's  Below Secondary  no_of_trainings  \
is_promoted                                                                   
0                    0.268329    0.671340         0.014719         1.257639   
1                    0.315124    0.644387         0.014353         1.203299   

                   age  previous_year_rating  length_of_service  \
is_promoted                                                       
0            34.844037              3.021221           5.879398   
1            34.372965              3.696658           5.716367   

             KPIs_met >80%  awards_won?  avg_training_score  
is_promoted                                                  
0                 0.319685     0.014180           62.647686  
1                 0.698800     0.119751           71.325193

In [19]:
# writing the final predicted values to an excel file
from pandas import ExcelWriter

writer = pd.ExcelWriter('WNS_RF_predicted_values.xlsx', engine='xlsxwriter')
WNS_test_dframe.to_excel(writer, sheet_name='Sheet1', columns = (['employee_id','is_promoted']), index_label=None)
writer.save()

In [25]:
mt = confusion_matrix(Y_pred, Y_test)
print("False positive rate : %f %%" % ((mt[0][1] / float(sum(mt[0])))*100))
print('False negative rate : %f %%' % ( (mt[1][0] / float(sum(mt[1]))*100)))

False positive rate : 5.658641 %
False negative rate : 36.969697 %
